Add Support for Text Formatting in Copy and Paste Operations
chrrs/scribble pull request #14
Opened 2024-08-11 09:37 UTC by wiskiw

Hi
I just added a feature that lets users cut, copy, and paste text in the book with its formatting. This PR addresses to the [feature request #6](https://github.com/chrrs/scribble/issues/6).

### Changes Made:
- Added tests for the original insertion and replacement methods to make sure that my changes didn't break any existing functionality. But there's still room to cover more test cases.
- Introduced new methods to the `RichText` class for [inserting](https://github.com/wiskiw/ScribbleMC/blob/6e3c2875fa7262096549ddb6b564c2e39e97f3b5/src/main/java/me/chrr/scribble/book/RichText.java#L314) and [replacing](https://github.com/wiskiw/ScribbleMC/blob/6e3c2875fa7262096549ddb6b564c2e39e97f3b5/src/main/java/me/chrr/scribble/book/RichText.java#L230) text using a list of `RichText.Segments`.
- Update `RichSelectionManager` copy and cut methods to return text with formatting. 
- The original [`insert`](https://github.com/wiskiw/ScribbleMC/blob/6e3c2875fa7262096549ddb6b564c2e39e97f3b5/src/main/java/me/chrr/scribble/book/RichText.java#L284C21-L284C27) and [`replace`](https://github.com/wiskiw/ScribbleMC/blob/6e3c2875fa7262096549ddb6b564c2e39e97f3b5/src/main/java/me/chrr/scribble/book/RichText.java#L225) methods remain available, but now use the updated logic.

Let me know if you spot any issues or further improvements needed.

meow 🐈

2024-08-12 09:10 UTC, chrrs requested changes
Thank you so much for the pull request! This is one of the issues I've been struggling with getting all the details just right, but it looks like you've solved the problems I had with my implementation. The tests will also definitely be very useful, thank you for those!

I've made a few comments about things I think should be changed.

2024-08-12 12:12 UTC, wiskiw commented on src/main/java/me/chrr/scribble/book/RichText.java
> +                    Optional.ofNullable(colorAndModifiersFromOffset.getLeft()).orElse(Formatting.RESET),
yeah, I saw the comment, and yes in this case `null` should not be possible. But I want to rely on the `getCommonFormat` method's signature only, and not on method implementation details. So I added this check.
The `Formatting.RESET` should not break anything here, so I used it as a default value.

2024-08-12 13:56 UTC, chrrs commented on src/main/java/me/chrr/scribble/book/RichText.java
> +                    Optional.ofNullable(colorAndModifiersFromOffset.getLeft()).orElse(Formatting.RESET),
That's fair! In that case though, `BLACK` should still be used, as `RESET` is slightly broken in books.

2024-08-12 13:58 UTC, wiskiw commented on src/main/java/me/chrr/scribble/book/RichText.java
> +                    Optional.ofNullable(colorAndModifiersFromOffset.getLeft()).orElse(Formatting.RESET),
I just realize that why you did use `BACK` instead of `RESET` 😅 
I'm on it right now

2024-08-12 16:54 UTC, wiskiw commented on src/main/java/me/chrr/scribble/book/RichText.java
> +        // A non-formatted string copied from the book will always contain the RESET formatting tag.
yes, I was wrong in this comment. But I kept the check `if a string contains only RESET formatting tag without any other color/modifiers`. See [this](https://github.com/chrrs/scribble/pull/14#discussion_r1714105171) comment

2024-08-12 17:02 UTC, wiskiw commented
@chrrs There is one more questions about the user experience with the copy logic. Should we keep the option to copy text from a book without formatting tags? Because with the PR the user will lose this ability.

2024-08-16 09:13 UTC, chrrs commented on src/main/java/me/chrr/scribble/book/RichSelectionManager.java
> +        }
That should be fine then!

2024-08-16 09:14 UTC, chrrs approved these changes
Sorry for the small delay, looks good to me now!

2024-08-16 09:17 UTC, chrrs commented
> There is one more questions about the user experience with the copy logic. Should we keep the option to copy text from a book without formatting tags? Because with the PR the user will lose this ability.

I was thinking there could be some shortcut to copy/paste without formatting, for example Ctrl+Shift+C and Ctrl+Shift+V (to match other programs like Word, which have similar shortcuts). It's up to you wether you want to add this in this PR or leave it for later.

2024-08-16 09:23 UTC, wiskiw commented
> there could be some shortcut to copy/paste without formatting, for example Ctrl+Shift+C and Ctrl+Shift+V 

Sounds good. I'll leave this implementation for another PR.

2024-08-16 09:29 UTC, merged

2024-08-18 14:44 UTC, chrrs commented
> Ctrl+Shift+C and Ctrl+Shift+V 

I've added this in 083161a!